# Generated by Django 5.2.1 on 2025-05-28 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('louee', 'Louée'), ('vendue', 'Vendue'), ('masque', 'Masqué')], default='disponible', max_length=20)),
                ('localisation', models.CharField(max_length=255)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15)),
                ('option', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proprietes/')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bien_app.propriete')),
            ],
        ),
    ]
