# Generated by Django 5.2.1 on 2025-05-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('louee', 'Louée'), ('vendue', 'Vendue'), ('masque', 'Masqué')], max_length=30),
        ),
    ]
