# Generated by Django 5.2.1 on 2025-05-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien_app', '0002_alter_propriete_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='slug',
        ),
    ]
