# Generated by Django 5.2.1 on 2025-05-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_app', '0003_remove_propriete_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(choices=[('APPART', 'Appartement'), ('VILLA', 'Villa'), ('MAISON', 'Terrain'), ('LOCAL', 'Local commercial'), ('PARKING', 'Parking')], max_length=30),
        ),
    ]
