# Generated by Django 5.2.2 on 2025-06-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_clientprofile_agent'),
        ('bien_app', '0004_alter_propriete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='bailleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes', to='auth_app.bailleurprofile'),
        ),
    ]
