# Generated by Django 5.2.2 on 2025-06-11 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_app', '0005_propriete_bailleur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='bailleur',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Bailleur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietes', to=settings.AUTH_USER_MODEL),
        ),
    ]
