# Generated by Django 5.2.2 on 2025-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_app', '0007_alter_propriete_bailleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='usage',
            field=models.CharField(max_length=250),
        ),
    ]
