# Generated by Django 5.2.2 on 2025-06-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0010_alter_clientprofile_agent'),
        ('bien_app', '0007_alter_propriete_bailleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souhaitee', models.DateField()),
                ('date_confirmee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé par l’agent'), ('ANNULE_CLIENT', 'Annulé par le client'), ('REFUSE_AGENT', 'Refusé par l’agent'), ('VALIDE_CLIENT', 'Accepté par le client')], default='EN_ATTENTE', max_length=20)),
                ('commentaire_client', models.TextField(blank=True)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_agent', to='auth_app.agentprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_client', to='auth_app.clientprofile')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_app.propriete')),
            ],
        ),
    ]
