# Generated by Django 5.2.2 on 2025-06-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date_confirmee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
    ]
