# Generated by Django 5.2.2 on 2025-06-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_clientprofile_agent'),
        ('messenger', '0002_alter_discussion_id_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='id_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='auth_app.agentprofile'),
        ),
    ]
