# Generated by Django 5.2.1 on 2025-05-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent'), ('MANAGER', 'Manager')], default='', max_length=10),
        ),
    ]
