# Generated by Django 5.2.1 on 2025-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent'), ('MANAGER', 'Manager')], default='CLIENT', max_length=10),
        ),
    ]
