# Generated by Django 5.2.2 on 2025-06-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_adresse_alter_customuser_user_type'),
        ('bien_app', '0004_alter_propriete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favoris_clients', to='bien_app.propriete'),
        ),
    ]
