# Generated by Django 5.2.2 on 2025-06-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_clientprofile_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
    ]
