# Generated by Django 5.2.2 on 2025-06-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_clientprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent'), ('MANAGER', 'Manager'), ('BAILLEUR', 'Bailleur')], default='CLIENT', max_length=10),
        ),
        migrations.CreateModel(
            name='BailleurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'BAILLEUR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
