# Generated by Django 5.2.2 on 2025-06-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_clientprofile_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='auth_app.agentprofile'),
        ),
    ]
