# Generated by Django 5.2 on 2025-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain')], max_length=30)),
                ('usage', models.CharField(choices=[('residentiel', 'Résidentiel'), ('commercial', 'Commercial')], max_length=30)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('louee', 'Louée'), ('vendue', 'Vendue'), ('masquee', 'Masquée')], default='masquee', max_length=20)),
                ('localisation', models.CharField(max_length=255)),
                ('superficie', models.FloatField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('option', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('last_date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
